name: SayHello

on:
  push:
    branches:
      - main
      - develop

jobs:
  welcome:
    runs-on: ubuntu-latest

    steps:
      - name: Download your code ðŸ’¾
        uses: actions/checkout@v2

      - name: Say something ðŸ“¢
        run: echo "hello world"
        
  hello-main:
    runs-on: ubuntu-latest

    steps:
      - name: Download your code ðŸ’¾
        uses: actions/checkout@v2

      - name: Verify main branch ðŸ””
        if: ${{github.ref == 'refs/heads/main'}}
        run: echo "hello main"

      - name: Verify develop branch ðŸ””
        if: ${{github.ref == 'refs/heads/develop'}}
        run: echo "hello develop"


      
